HOST=1
PORTAL_GUI_URL=
PORTAL_AUTH_URL=
# -------------------- Proxy --------------------
HTTP_PROXY=http://10.116.42.122:3128
HTTPS_PROXY=http://10.116.42.122:3128
NO_PROXY=tccloud2.toshiba.co.jp,gitlab.tsdv.com.vn
